import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../data/models/bug_report_model.dart';

class BugService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static const String supportEmail = 'vnoptocare@gmail.com';

  /// Save bug report to Firebase
  Future<String?> saveBugReport(BugReportModel report) async {
    try {
      debugPrint('[BugService] 🐛 Saving bug report to Firebase...');

      final docRef = await _firestore
          .collection('BugReports')
          .add(report.toFirestore());

      debugPrint('[BugService] ✅ Bug report saved to Firebase: ${docRef.id}');
      return docRef.id;
    } catch (e) {
      debugPrint('[BugService] ⚠️ Error saving bug report to Firebase: $e');
      return null;
    }
  }

  /// Format the email body professionally for bug reports
  String formatBugEmailBody({
    required BugReportModel report,
    required String reportId,
  }) {
    final dateStr = DateFormat('MMMM dd, yyyy').format(report.timestamp);
    final timeStr = DateFormat('h:mm a').format(report.timestamp);

    return '''
==================================================

           🚀 VISIAXX DIGITAL EYE CLINIC
                Official Bug Report

==================================================

⚠️ IMPORTANT: PLEASE ATTACH SCREENSHOTS OF THE ISSUE 
    TO THIS EMAIL FOR FASTER RESOLUTION.

==================================================

📝 REPORT INFORMATION

Reference ID: #$reportId
Date: $dateStr at $timeStr
Priority: HIGH (URGENT)
Type: Bug / Technical Issue Analysis

==================================================

👤 USER PROFILE

Name: ${report.userName.toUpperCase()}
Age: ${report.userAge} Years
Status: ✅ Verified App User
Platform: Visiaxx Mobile Application

==================================================

🐞 ISSUE DESCRIPTION

"${report.description}"

==================================================

🛡️ CONFIDENTIALITY NOTICE

This report is CONFIDENTIAL and intended exclusively for 
Vision Optocare Development Team. Unauthorized access, 
distribution, or disclosure is strictly prohibited.

==================================================

⚙️ SYSTEM NOTIFICATION

Generated By: Visiaxx Bug Reporting System
Organization: Vision Optocare Private Limited
Location: Mumbai, Maharashtra, India

📧 vnoptocare@gmail.com
🌐 https://visionoptocare.com/home

© 2026 Vision Optocare. All Rights Reserved.

==================================================

                    END OF REPORT

==================================================
''';
  }

  /// Send email notification via user's email client
  Future<bool> sendBugEmail(BugReportModel report, {String? reportId}) async {
    try {
      debugPrint('[BugService] 📧 Opening user email client for bug report...');

      final refId = reportId ?? 'PENDING';
      final emailBody = formatBugEmailBody(report: report, reportId: refId);
      final subject =
          '[URGENT] Bug Report - Visiaxx Digital Eye Clinic - ${report.userName}';

      final Uri emailUri = Uri(
        scheme: 'mailto',
        path: supportEmail,
        query:
            'subject=${Uri.encodeComponent(subject)}&body=${Uri.encodeComponent(emailBody)}',
      );

      debugPrint('[BugService] 🚀 Launching email URI...');

      if (await canLaunchUrl(emailUri)) {
        await launchUrl(emailUri);
        debugPrint('[BugService] ✅ Email client opened successfully');
        return true;
      } else {
        debugPrint('[BugService] ⚠️ Could not launch email client');
        return false;
      }
    } catch (e) {
      debugPrint('[BugService] ⚠️ Error opening email client: $e');
      return false;
    }
  }

  /// Submit bug report (save + email)
  Future<bool> submitBugReport(BugReportModel report) async {
    try {
      debugPrint('[BugService] 🛡️ Starting bug report submission...');

      // 1. Save to Firebase
      final reportId = await saveBugReport(report);
      if (reportId == null) {
        debugPrint('[BugService] ⚠️ Failed to save bug report to Firebase');
        return false;
      }

      // 2. Open email client
      final emailSent = await sendBugEmail(report, reportId: reportId);

      // 3. Update report with email status
      try {
        await _firestore.collection('BugReports').doc(reportId).update({
          'emailSent': emailSent,
        });
        debugPrint('[BugService] ✅ Updated email status in Firebase');
      } catch (e) {
        debugPrint('[BugService] ⚠️ Failed to update email status: $e');
      }

      debugPrint('[BugService] ✅ Bug report submission completed successfully');
      return true;
    } catch (e) {
      debugPrint('[BugService] ⚠️ Critical error submitting bug report: $e');
      return false;
    }
  }
}
