import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/extensions/theme_extension.dart';
import '../../../core/services/consultation_service.dart';
import '../../../core/services/auth_service.dart';
import '../../../data/models/time_slot_model.dart';
import '../../home/widgets/app_bar_widget.dart';

class DoctorSlotManagementScreen extends StatefulWidget {
  const DoctorSlotManagementScreen({super.key});

  @override
  State<DoctorSlotManagementScreen> createState() =>
      _DoctorSlotManagementScreenState();
}

class _DoctorSlotManagementScreenState
    extends State<DoctorSlotManagementScreen> {
  final _consultationService = ConsultationService();
  final _authService = AuthService();
  DateTime _selectedDate = DateTime.now();
  List<TimeSlotModel> _slots = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadSlots();
  }

  Future<void> _loadSlots() async {
    setState(() => _isLoading = true);
    final uid = _authService.currentUserId;
    if (uid != null) {
      final slots = await _consultationService.getAllSlotsForDate(
        uid,
        _selectedDate,
      );
      setState(() {
        _slots = slots;
        _isLoading = false;
      });
    }
  }

  Future<void> _addSlot() async {
    final TimeOfDay? picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );

    if (picked != null) {
      final uid = _authService.currentUserId;
      if (uid == null) return;

      final startTime = picked.format(context);
      // Simple end time estimation: +30 mins
      final endDateTime = DateTime(
        _selectedDate.year,
        _selectedDate.month,
        _selectedDate.day,
        picked.hour,
        picked.minute,
      ).add(const Duration(minutes: 30));
      final endTime = TimeOfDay.fromDateTime(endDateTime).format(context);

      final newSlot = TimeSlotModel(
        id: '', // Generated by service
        doctorId: uid,
        date: DateTime(
          _selectedDate.year,
          _selectedDate.month,
          _selectedDate.day,
        ),
        startTime: startTime,
        endTime: endTime,
        status: SlotStatus.available,
      );

      final success = await _consultationService.createSlot(uid, newSlot);
      if (success) {
        _loadSlots();
      }
    }
  }

  Future<void> _deleteSlot(String slotId) async {
    final uid = _authService.currentUserId;
    if (uid != null) {
      final success = await _consultationService.deleteSlot(
        uid,
        _selectedDate,
        slotId,
      );
      if (success) {
        _loadSlots();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const AppBarWidget(title: 'Manage Slots'),
      body: Column(
        children: [
          _buildDatePicker(),
          const Divider(),
          Expanded(
            child: _isLoading
                ? const Center(child: CircularProgressIndicator())
                : _slots.isEmpty
                ? _buildEmptyState()
                : _buildSlotsList(),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _addSlot,
        backgroundColor: context.primary,
        icon: const Icon(Icons.add, color: AppColors.white),
        label: const Text('Add Slot', style: TextStyle(color: AppColors.white)),
      ),
    );
  }

  Widget _buildDatePicker() {
    return Container(
      height: 100,
      padding: const EdgeInsets.symmetric(vertical: 16),
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        padding: const EdgeInsets.symmetric(horizontal: 16),
        itemCount: 30, // Next 30 days
        itemBuilder: (context, index) {
          final date = DateTime.now().add(Duration(days: index));
          final isSelected = DateUtils.isSameDay(date, _selectedDate);

          return Padding(
            padding: const EdgeInsets.only(right: 12),
            child: InkWell(
              onTap: () {
                setState(() => _selectedDate = date);
                _loadSlots();
              },
              borderRadius: BorderRadius.circular(16),
              child: Container(
                width: 60,
                decoration: BoxDecoration(
                  color: isSelected ? context.primary : context.surface,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    color: isSelected
                        ? context.primary
                        : context.dividerColor.withValues(alpha: 0.1),
                  ),
                  boxShadow: isSelected
                      ? [
                          BoxShadow(
                            color: context.primary.withValues(alpha: 0.3),
                            blurRadius: 8,
                            offset: const Offset(0, 4),
                          ),
                        ]
                      : null,
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      DateFormat('E').format(date),
                      style: TextStyle(
                        fontSize: 12,
                        color: isSelected
                            ? AppColors.white
                            : AppColors.textTertiary,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      DateFormat('d').format(date),
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: isSelected
                            ? AppColors.white
                            : AppColors.textSecondary,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildSlotsList() {
    return ListView.builder(
      padding: const EdgeInsets.all(24),
      itemCount: _slots.length,
      itemBuilder: (context, index) {
        final slot = _slots[index];
        final isBooked = slot.status == SlotStatus.booked;

        return Card(
          elevation: 0,
          margin: const EdgeInsets.only(bottom: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
            side: BorderSide(
              color: Theme.of(context).dividerColor.withValues(alpha: 0.1),
            ),
          ),
          child: ListTile(
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 20,
              vertical: 8,
            ),
            leading: Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: (isBooked ? Colors.orange : Colors.green).withValues(
                  alpha: 0.1,
                ),
                shape: BoxShape.circle,
              ),
              child: Icon(
                isBooked ? Icons.lock : Icons.timer,
                color: isBooked ? Colors.orange : Colors.green,
              ),
            ),
            title: Text(
              '${slot.startTime} - ${slot.endTime}',
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            subtitle: Text(
              isBooked ? 'Booked' : 'Available',
              style: TextStyle(
                color: isBooked ? Colors.orange : Colors.green,
                fontWeight: FontWeight.w600,
              ),
            ),
            trailing: isBooked
                ? null
                : IconButton(
                    icon: const Icon(Icons.delete_outline, color: Colors.red),
                    onPressed: () => _deleteSlot(slot.id),
                  ),
          ),
        );
      },
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.calendar_today_outlined,
            size: 64,
            color: AppColors.textTertiary.withValues(alpha: 0.3),
          ),
          const SizedBox(height: 16),
          const Text('No slots created for this date'),
          const SizedBox(height: 8),
          Text(
            'Tap "Add Slot" to set your availability',
            style: TextStyle(fontSize: 12, color: AppColors.textTertiary),
          ),
        ],
      ),
    );
  }
}
