// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh7sAldIwlNO8p9PilQAUHwdI8d_lKwKY',
    appId: '1:172938802712:web:5ed385ca39efe6265c356d',
    messagingSenderId: '172938802712',
    projectId: 'visiaxx-fd860',
    authDomain: 'visiaxx-fd860.firebaseapp.com',
    storageBucket: 'visiaxx-fd860.firebasestorage.app',
    measurementId: 'G-5BWJN272TE',
    databaseURL: 'https://visiaxx-fd860-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYR7nXIjj6TSmaAIWbz-3vCdjz3b-AP0',
    appId: '1:172938802712:android:208463a0bb1fc65b5c356d',
    messagingSenderId: '172938802712',
    projectId: 'visiaxx-fd860',
    storageBucket: 'visiaxx-fd860.firebasestorage.app',
    databaseURL: 'https://visiaxx-fd860-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAevTMy-QfSAA6BNd8tZjpKngiRkHeXGEM',
    appId: '1:172938802712:ios:32eca8b31ce5562f5c356d',
    messagingSenderId: '172938802712',
    projectId: 'visiaxx-fd860',
    storageBucket: 'visiaxx-fd860.firebasestorage.app',
    iosBundleId: 'com.example.visiaxx',
    databaseURL: 'https://visiaxx-fd860-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAevTMy-QfSAA6BNd8tZjpKngiRkHeXGEM',
    appId: '1:172938802712:ios:32eca8b31ce5562f5c356d',
    messagingSenderId: '172938802712',
    projectId: 'visiaxx-fd860',
    storageBucket: 'visiaxx-fd860.firebasestorage.app',
    iosBundleId: 'com.example.visiaxx',
    databaseURL: 'https://visiaxx-fd860-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh7sAldIwlNO8p9PilQAUHwdI8d_lKwKY',
    appId: '1:172938802712:web:3c3f6e18d3b05bde5c356d',
    messagingSenderId: '172938802712',
    projectId: 'visiaxx-fd860',
    authDomain: 'visiaxx-fd860.firebaseapp.com',
    storageBucket: 'visiaxx-fd860.firebasestorage.app',
    measurementId: 'G-WMLKEKVXK0',
    databaseURL: 'https://visiaxx-fd860-default-rtdb.firebaseio.com',
  );
}
